# Dosya adÄ±: docker-compose.yml
version: '3.8'

services:

  hukuk_api:
    build: .
    container_name: hukuk_backend
    restart: unless-stopped 
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./chromadb:/app/chromadb
      - ./chromadb_summaries:/app/chromadb_summaries
